#!/bin/sh
#
# Copyright (c) 2015 The Linux Foundation. All rights reserved.
# Copyright (c) 2011-2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

ipq40xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	linksys,ea6350v3)
		ucidef_set_interfaces_lan_wan "eth0.1" "eth0.2"
		ucidef_add_switch "switch0" \
			"0t@eth0" "1:lan" "2:lan" "3:lan" "4:lan" "5:wan"
		;;
	*)
		echo "Unsupported hardware. Network interfaces not initialized"
		;;
	esac
}

ipq40xx_setup_macs()
{
	local board="$1"

	case "$board" in
	linksys,ea6350v3)
		wan_mac=$(mtd_get_mac_ascii devinfo hw_mac_addr)
		lan_mac=$(macaddr_add "$wan_mac" 1)
		;;
	esac

	[ -n "$lan_mac" ] && ucidef_set_interface_macaddr "lan" $lan_mac
	[ -n "$wan_mac" ] && ucidef_set_interface_macaddr "wan" $wan_mac
}

board_config_update
board=$(board_name)
ipq40xx_setup_interfaces $board
ipq40xx_setup_macs $board
board_config_flush

exit 0
